### PR TITLE
Initial Implementation of Spritesheet/Dataset Maker for Development Workbench

### PR DESCRIPTION
**Pull request by akhil-rana**
## Description
Spritesheet maker has been shifted from [caracal #38](https://github.com/camicroscope/Caracal/pull/38) to here. 
With the same features and should have more stability.
This works with [caMicroscope #409](https://github.com/camicroscope/caMicroscope/pull/409)

- All the files are saved into a user specific folder under: `/images/datasets/<userFolder>` and the folder is deleted after the task is completed.

## How Has This Been Tested?
Briefly tested on Firefox (78.0), Chrome (84.0), Brave (1.9.80) on Windows 10 and Linux (arch)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by birm** [comment]
Also, thanks for dealing with my architecture comments :)

**Comment by akhil-rana** [comment]
@birm 
Do you think we should have a new branch here too?

**Comment by birm** [comment]
I could be convinced either way. What do you think?

**Comment by akhil-rana** [comment]
I won't need much of more development here I think. And the new code shouldn't affect normal functionality in `develop`. If you don't mind having useless code in `develop` for a while then let's keep it here otherwise a new branch.

**Pull request merged**
