### PR TITLE
BioFormats

### PR DESCRIPTION
**Pull request by CGDogan**
Ryan, could you please rebuild and update the Dockerhub image for https://github.com/camicroscope/image-decoders/tree/main please? These are the changes from the last time: https://github.com/camicroscope/image-decoders/compare/ab596801cc8b6c5f8e45aa239ca7310f7121356b...e24cce6b905f9d6316e760dd4a3806104d90b883

https://downloads.openmicroscopy.org/images/Olympus-FluoView/imagesc-71616/ is a good testfile for bioformats, I think our code works well.

One solution I couldn't solve (and I'm not sure if it's worth investing time in this, you decide) is that despite having tried two methods to change this, it continues to print at DEBUG level instead of warning level, so console output is helpful but takes space.

### CODE REVIEW

**Comment by birm** [comment]
Do you like this over dockerhub? https://github.com/camicroscope/image-decoders/pkgs/container/image-decoders

**Comment by CGDogan** [comment]
@birm I would prefer DockerHub as when I first tried to run caMicroscope I got an auth failure which you also got and which led you to then remove it: https://github.com/camicroscope/Distro/commit/7647bb529756d40fd7067b1097958291986091fd

https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages says 1 GB per month transfer limit which is too little [but much higher for docker hub](https://jfrog.com/de/devops-tools/article/comparing-docker-hub-and-github-container-registry/) so I would choose Docker Hub

**Comment by birm** [comment]
I've pushed to https://hub.docker.com/r/camicroscope/image-decoders/tags

The issue with iipimage on ghcr was apparently related to the package defaulting to private for baffling reasons. I like that it's easier to push with the ci pipelines we have now. Maybe we should figure out a better plan for automatic package ci/cd?

In any case, I'll test this change shortly.

**Comment by birm** [comment]
It looks like the thumbnail doesn't work for bioformats? http://localhost:4010/loader/data/thumbnail/20220824_4492_cord_dapi__iba568_60x.oib returned {"type": "bioformats", "error": "module 'BFBridge.python.utils' has no attribute 'make_pil_image'"}; does this match your observation?

Similarly, I think you know this, but it looks like iip doesn't support this as is. http://localhost:4010/img/IIP/raw/?DeepZoom=/images/oibTest.oib.dzi just returned the html iipimage screen.

**Comment by birm** [comment]
@CGDogan I saw your change, and thought I'd update you on the thumbnail response for the same image: {"type": "bioformats", "error": "make_pil_image: only 3 or 4 channels supported currently"}

**Comment by birm** [comment]
In any case, I'm content to merge this, as the additional changes are needed in other repos; the oib support in the tileserver, updating the list of supported formats in the caMicroscope frontend, and possibly make_pil_images in bf bridge. Please let me know if you'd like me to approve this PR.

**Comment by birm** [comment]
I think it's ok to use both ghcr and dockerhub concurrently as we are doing now. The documentation on billing is unclear, but I think that public images are not subject to these limits. Worth keeping an eye on. Otherwise, we'll get issues like now where I'd forgotten that my new work laptop is a mac M1, which produced an image with some issues on basically every other host. (I've since re-pushed image-decoders).

**Review by birm — APPROVED** [review]

**Pull request merged**
